//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNavigationPropertiesExercise_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public short JobID { get; set; }
        public Nullable<byte> JobLevel { get; set; }
        public string PublisherID { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
