//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETEntityFrameworkExercise_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string StoreID { get; set; }
        public string OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public short Quantity { get; set; }
        public string Payterms { get; set; }
        public string TitleID { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Title Title { get; set; }
    }
}
