//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETEntityFrameworkExercise_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitlesAuthors
    {
        public string AuthorID { get; set; }
        public string TitleID { get; set; }
        public Nullable<byte> AuthorOrder { get; set; }
        public Nullable<int> Royaltyper { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Title Title { get; set; }
    }
}
