//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CUD_Exercise_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public string DiscountType { get; set; }
        public string StoreID { get; set; }
        public Nullable<short> LowQuantity { get; set; }
        public Nullable<short> HighQuantity { get; set; }
        public decimal DiscountRate { get; set; }
    }
}
