//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CUD_Exercise_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Title()
        {
            this.Sales = new HashSet<Sale>();
            this.TitleAuthors = new HashSet<TitleAuthor>();
        }
    
        public string TitleID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string PublisherID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<int> Royalty { get; set; }
        public Nullable<int> YearToDateSales { get; set; }
        public string Notes { get; set; }
        public System.DateTime PublicationDate { get; set; }
    
        public virtual Publisher Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitleAuthor> TitleAuthors { get; set; }
    }
}
